nohup: ignoring input
Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-3dd342df.pth" to /home/en520-twong53/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-3dd342df.pth
  0%|          | 0.00/20.5M [00:00<?, ?B/s] 11%|█         | 2.16M/20.5M [00:00<00:00, 22.6MB/s] 41%|████▏     | 8.48M/20.5M [00:00<00:00, 48.3MB/s] 71%|███████   | 14.5M/20.5M [00:00<00:00, 55.1MB/s] 99%|█████████▊| 20.2M/20.5M [00:00<00:00, 56.8MB/s]100%|██████████| 20.5M/20.5M [00:00<00:00, 53.0MB/s]
Traceback (most recent call last):
  File "/scratch4/en520-lmorove1/en520-twong53/melanoma/classification/main_3.py", line 58, in <module>
    main_3()
  File "/scratch4/en520-lmorove1/en520-twong53/melanoma/classification/main_3.py", line 38, in main_3
    model = get_efficientnet(num_classes=1, pretrained=True)
  File "/scratch4/en520-lmorove1/en520-twong53/melanoma/classification/models.py", line 5, in get_efficientnet
    model = efficientnet_b0(weights=EfficientNet_B0_Weights.IMAGENET1K_V1 if pretrained else None)
  File "/home/en520-twong53/.conda/envs/mlma2025/lib/python3.9/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "/home/en520-twong53/.conda/envs/mlma2025/lib/python3.9/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "/home/en520-twong53/.conda/envs/mlma2025/lib/python3.9/site-packages/torchvision/models/efficientnet.py", line 770, in efficientnet_b0
    return _efficientnet(
  File "/home/en520-twong53/.conda/envs/mlma2025/lib/python3.9/site-packages/torchvision/models/efficientnet.py", line 360, in _efficientnet
    model.load_state_dict(weights.get_state_dict(progress=progress, check_hash=True))
  File "/home/en520-twong53/.conda/envs/mlma2025/lib/python3.9/site-packages/torchvision/models/_api.py", line 90, in get_state_dict
    return load_state_dict_from_url(self.url, *args, **kwargs)
  File "/home/en520-twong53/.conda/envs/mlma2025/lib/python3.9/site-packages/torch/hub.py", line 766, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/en520-twong53/.conda/envs/mlma2025/lib/python3.9/site-packages/torch/hub.py", line 663, in download_url_to_file
    raise RuntimeError(f'invalid hash value (expected "{hash_prefix}", got "{digest}")')
RuntimeError: invalid hash value (expected "3dd342df", got "7f5810bc96def8f7552d5b7e68d53c4786f81167d28291b21c0d90e1fca14934")
